Script started on Fri 13 Mar 2015 03:26:41 AM PDT
]0;sherman@ubuntu: ~/projects/rshellsherman@ubuntu:~/projects/rshell$ cd [K[K[Kbin/rshell 
[sherman@ubuntu]/home/sherman/projects/rshell>>ls .
[32;1mcs100-runtests.sh  [0mtypescript  Makefile  [34;1msrc  [0m[34;1mbin  [0m[34;1mtests  [0mREADME.md  LICENSE  

[sherman@ubuntu]/home/sherman/projects/rshell>>cd .
[sherman@ubuntu]/home/sherman/projects/rshell>>cd ..
[sherman@ubuntu]/home/sherman/projects>>cd rshell/sr	c
[sherman@ubuntu]/home/sherman/projects/rshell/src>>cd rshell.cpp
chdir error: Not a directory
[sherman@ubuntu]/home/sherman/projects/rshell/src>>cd /dir/not/exitst
chdir error: No such file or directory
[sherman@ubuntu]/home/sherman/projects/rshell/src>>cd /home/
[sherman@ubuntu]/home>>cd /root
chdir error: Permission denied
[sherman@ubuntu]/home>>ls
[34;1msherman  [0m

[sherman@ubuntu]/home>>/bin/ls
sherman
[sherman@ubuntu]/home>>md5sum >/dev/null
^C[sherman@ubuntu]/home>>ficonfig        ifconfig > /dev/null
[sherman@ubuntu]/home>>mk s kfs / >   --help ? >/dev/null
[sherman@ubuntu]/home>>nonexist  command
execv error: No such file or directory
[sherman@ubuntu]/home>>cat
^C[sherman@ubuntu]/home>>top
[?1h=[?25l[H[2J(B[mtop - 03:28:17 up  7:06,  3 users,  load average: 0.02, 0.06, 0.08(B[m[39;49m(B[m[39;49m[K
Tasks:(B[m[39;49m[1m 456 (B[m[39;49mtotal,(B[m[39;49m[1m   1 (B[m[39;49mrunning,(B[m[39;49m[1m 455 (B[m[39;49msleeping,(B[m[39;49m[1m   0 (B[m[39;49mstopped,(B[m[39;49m[1m   0 (B[m[39;49mzombie(B[m[39;49m(B[m[39;49m[K
%Cpu(s):(B[m[39;49m[1m  1.5 (B[m[39;49mus,(B[m[39;49m[1m  0.6 (B[m[39;49msy,(B[m[39;49m[1m  0.1 (B[m[39;49mni,(B[m[39;49m[1m 97.6 (B[m[39;49mid,(B[m[39;49m[1m  0.1 (B[m[39;49mwa,(B[m[39;49m[1m  0.0 (B[m[39;49mhi,(B[m[39;49m[1m  0.0 (B[m[39;49msi,(B[m[39;49m[1m  0.0 (B[m[39;49mst(B[m[39;49m(B[m[39;49m[K
KiB Mem: (B[m[39;49m[1m  1003512 (B[m[39;49mtotal,(B[m[39;49m[1m   926108 (B[m[39;49mused,(B[m[39;49m[1m    77404 (B[m[39;49mfree,(B[m[39;49m[1m    13648 (B[m[39;49mbuffers(B[m[39;49m(B[m[39;49m[K
KiB Swap:(B[m[39;49m[1m  1046524 (B[m[39;49mtotal,(B[m[39;49m[1m   135416 (B[m[39;49mused,(B[m[39;49m[1m   911108 (B[m[39;49mfree.(B[m[39;49m[1m   189888 (B[m[39;49mcached Mem(B[m[39;49m(B[m[39;49m[K
[K
[7m   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND     (B[m[39;49m[K
(B[m     7 root      20   0       0      0      0 S  3.4  0.0   0:05.79 rcu_sched   (B[m[39;49m[K
(B[m[1m  9402 sherman   20   0   25224   1776   1060 R  3.4  0.2   0:00.13 top         (B[m[39;49m[K
(B[m     1 root      20   0   33780   2216    812 S  0.0  0.2   0:03.90 init        (B[m[39;49m[K
(B[m     2 root      20   0       0      0      0 S  0.0  0.0   0:00.07 kthreadd    (B[m[39;49m[K
(B[m     3 root      20   0       0      0      0 S  0.0  0.0   0:00.31 ksoftirqd/0 (B[m[39;49m[K
(B[m     4 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0 (B[m[39;49m[K
(B[m     5 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:+ (B[m[39;49m[K
(B[m     8 root      20   0       0      0      0 S  0.0  0.0   0:03.94 rcuos/0     (B[m[39;49m[K
(B[m     9 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/1     (B[m[39;49m[K
(B[m    10 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/2     (B[m[39;49m[K
(B[m    11 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/3     (B[m[39;49m[K
(B[m    12 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/4     (B[m[39;49m[K
(B[m    13 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/5     (B[m[39;49m[K
(B[m    14 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/6     (B[m[39;49m[K
(B[m    15 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/7     (B[m[39;49m[K
(B[m    16 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/8     (B[m[39;49m[K
(B[m    17 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/9     (B[m[39;49m[K[?1l>[25;1H
[?12l[?25h[K[sherman@ubuntu]/home>>cat 
^Z[sherman@ubuntu]/home>>ps
   PID TTY          TIME CMD
  9370 pts/24   00:00:00 bash
  9382 pts/24   00:00:00 rshell
  9403 pts/24   00:00:00 cat
  9405 pts/24   00:00:00 ps
[sherman@ubuntu]/home>>fg
adsfaf
adsfaf
^C[sherman@ubuntu]/home>>ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=128 time=8.17 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=128 time=7.99 ms
^Z[sherman@ubuntu]/home>>bg
[sherman@ubuntu]/home>>64 bytes from 8.8.8.8: icmp_seq=3 ttl=128 time=8.04 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=128 time=7.65 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=128 time=7.93 ms
64 bytes from 8.8.8.8: icmp_seq=6 ttl=128 time=8.13 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=128 time=7.68 ms
64 bytes from 8.8.8.8: icmp_seq=8 ttl=128 time=7.72 ms
64 bytes from 8.8.8.8: icmp_seq=9 ttl=128 time=14.4 ms
64 bytes from 8.8.8.8: icmp_seq=10 ttl=128 time=7.80 ms
64 bytes from 8.8.8.8: icmp_seq=11 ttl=128 time=16.7 ms
64 bytes from 8.8.8.8: icmp_seq=12 ttl=128 time=7.54 ms
64 bytes from 8.8.8.8: icmp_seq=13 ttl=128 time=7.71 ms
64 bytes from 8.8.8.8: icmp_seq=14 ttl=128 time=7.54 ms
64 bytes from 8.8.8.8: icmp_seq=15 ttl=128 time=8.23 ms
64 bytes from 8.8.8.8: icmp_seq=16 ttl=128 time=8.11 ms
ls
[34;1msherman  [0m

[sherman@ubuntu]/home>>exit
]0;sherman@ubuntu: ~/projects/rshellsherman@ubuntu:~/projects/rshell$ exit
exit

Script done on Fri 13 Mar 2015 03:29:04 AM PDT
